apiVersion: v1
kind: Pod
metadata:
  name: my-config
  namespace: default
spec:
  containers:
    - name: my-container
      image: nginx:latest
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: firstname
        - name: SECONDNAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: secondname
  restartPolicy: Never
